### ISSUE TITLE
Reusing your code / licensing terms?

### ISSUE THREAD

**Issue by glutanimate** [mlisbit/pyqt_snake#1]
Hi there,

Thank you for sharing this fun little game!

I was thinking of adding a modified version of your code to one of my projects (as a small easter egg of sorts) and I was wondering if you'd be OK with that. If so, which license can I assume?

Thanks a lot in advance!

**Comment by mlisbit** [comment]
License added :)

**Comment by glutanimate** [comment]
Thank you! Appreciate it.
